name: Canik
favicon: null
layout_spectrum: 0.74277
typography_spectrum: 0.34537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#613cdd'
    - '#b2b935'
    - '#eaf439'
    - '#b96435'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
